---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: enforcer
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    doc:
        authors: Tucker J. Pelletier AKA virtualdogbert
        license: Apache2

